

export const metadata = {
    title: "Landing-page",
    description: "Generated by create next app",
  };


  export default function RootLayout({ children }) {
    return (
         <div>{children} </div>
    );
  }