import Navbar from "../Navbar/Navbar";



export const metadata = {
    title: "Blog",
    description: "Generated by create next app",
  };


  export default function RootLayout({ children }) {
    return (
         <><Navbar/>{children} </>
    );
  }